/*
Transactions
*/

CREATE TABLE BANK_ACCOUNT
(
	ACCOUNT_NO INT PRIMARY KEY,
    AMOUNT DECIMAL (10,2)
);

INSERT INTO BANK_ACCOUNT VALUES (11111, 10000);
INSERT INTO BANK_ACCOUNT VALUES (22222, 4000);
INSERT INTO BANK_ACCOUNT VALUES (33333, 7500);
INSERT INTO BANK_ACCOUNT VALUES (44444, 3600);

SELECT * FROM BANK_ACCOUNT WHERE ACCOUNT_NO IN (22222,44444);


/*
AUTO COMMIT - OFF
*/


UPDATE BANK_ACCOUNT SET AMOUNT = AMOUNT - 1000 WHERE ACCOUNT_NO = 22222;
UPDATE BANK_ACCOUNT SET AMOUNT = AMOUNT + 1000 WHERE ACCOUNT_NO = 44444;

COMMIT;

ROLLBACK;


SELECT * FROM BANK_ACCOUNT WHERE ACCOUNT_NO IN (22222,44444);


/*
TRANSACTION
	SUCCESS	- COMMIT
    FAILURE - ROLLBACK
*/



SHOW INDEX FROM BANK_ACCOUNT;

SHOW INDEX FROM CATEGORY;

SHOW INDEX FROM STUDENT;


SELECT * FROM STUDENT;

CREATE INDEX STUDENT_NAME_IDX ON STUDENT(STUDENT_NAME);

SELECT * FROM STATE;

SELECT * FROM STATE WHERE STATE_CD = 'AP'; /* INDEX SCAN */

SELECT * FROM STATE WHERE STATE_NAME = 'ANDHRA PRADESH'; /* TABLE SCAN */

EXPLAIN ANALYZE SELECT * FROM STATE WHERE STATE_CD = 'TL';
 

EXPLAIN ANALYZE SELECT * FROM STATE WHERE STATE_NAME = 'ANDHRA PRADESH';






