CREATE TABLE EMPLOYEE
(
	EMP_ID INT,
    EMP_NAME VARCHAR(100),
    JOINING_DATE DATE
);

INSERT INTO EMPLOYEE (EMP_ID, EMP_NAME, JOINING_DATE) VALUES (100, 'KUMAR', '2020-11-15');
INSERT INTO EMPLOYEE (EMP_ID, EMP_NAME, JOINING_DATE) VALUES (101, 'SUNITA', '2020-11-17');

SELECT EMP_ID, EMP_NAME from EMPLOYEE;




