
SELECT 
    *
FROM
    EMPLOYEE;
    
UPDATE EMPLOYEE 
SET 
    EMP_ID = EMP_ID + 10000;

UPDATE EMPLOYEE 
SET 
    emp_name = 'shiva'
WHERE
    EMP_ID = 102;
 
DELETE FROM EMPLOYEE 
WHERE
    EMP_ID = 106;
 
 
SELECT 
    MAX(JOINING_DATE)
FROM
    EMPLOYEE;
 
SELECT 
    MIN(JOINING_DATE)
FROM
    EMPLOYEE;
 
SELECT 
    MAX(JOINING_DATE), MIN(JOINING_DATE)
FROM
    EMPLOYEE;
 
SELECT 
    LOWER(EMP_NAME), UPPER(EMP_NAME)
FROM
    employee;

select count(emp_id) from employee where gender = 'F';
select count(emp_id) from employee where gender = 'M';



CREATE TABLE EMPLOYEE (
    EMP_ID INT,
    EMP_NAME VARCHAR(100),
    GENDER CHAR(1),
    JOINING_DATE DATE,
    DEPT_ID INT
);

INSERT INTO EMPLOYEE (EMP_ID, EMP_NAME, GENDER, JOINING_DATE, DEPT_ID) VALUES (100, 'KUMAR', 'M', '2020-11-15', 1000);
INSERT INTO EMPLOYEE (EMP_ID, EMP_NAME, GENDER, JOINING_DATE, DEPT_ID) VALUES (101, 'SUNITA', 'F', '2020-11-17', 1001);
INSERT INTO EMPLOYEE (EMP_ID, EMP_NAME, GENDER, JOINING_DATE, DEPT_ID) VALUES (102, 'PAVAN', 'M', '2020-11-10', 1002);
INSERT INTO EMPLOYEE (EMP_ID, EMP_NAME, GENDER, JOINING_DATE, DEPT_ID) VALUES (103, 'NITISH', 'M',  '2020-10-12', 1002);
INSERT INTO EMPLOYEE (EMP_ID, EMP_NAME, GENDER, JOINING_DATE, DEPT_ID) VALUES (104, 'ROHIT', 'M',  '2020-09-21', 1001);
INSERT INTO EMPLOYEE (EMP_ID, EMP_NAME, GENDER, JOINING_DATE, DEPT_ID) VALUES (105, 'VIRAT', 'M',  '2020-07-18', 1000);
INSERT INTO EMPLOYEE (EMP_ID, EMP_NAME, GENDER, JOINING_DATE, DEPT_ID) VALUES (106, 'SITA', 'F',  '2020-08-15', 1000);
INSERT INTO EMPLOYEE (EMP_ID, EMP_NAME, GENDER, JOINING_DATE, DEPT_ID) VALUES (107, 'TANUJA', 'F',  '2020-02-28', 1001);



select * from employee;


select * from employee limit 4 offset 4;


update employee set dept_id = 1002, emp_name='TANUJA SREE' where emp_id = 107;


show tables;

select * from employee ORDER BY JOINING_DATE DESC;

select * from employee order by dept_id;

select * from employee order by dept_id desc,emp_name;

select * from employee order by dept_id desc,emp_name desc;


select * from employee order by dept_id,emp_name desc;



DROP TABLE EMPLOYEE;

CREATE TABLE EMPLOYEE (
    EMP_ID INT,
    EMP_NAME VARCHAR(100),
    GENDER CHAR(1),
    JOINING_DATE DATE,
    PHONE_NUMBER BIGINT,
    DEPT_ID INT
);


INSERT INTO EMPLOYEE (EMP_ID, EMP_NAME, GENDER, JOINING_DATE, PHONE_NUMBER, DEPT_ID) VALUES (100, 'KUMAR', 'M', '2020-11-15', '9898985645', 1000);
INSERT INTO EMPLOYEE (EMP_ID, EMP_NAME, GENDER, JOINING_DATE, PHONE_NUMBER, DEPT_ID) VALUES (101, 'SUNITA', 'F', '2020-11-17', '876334455', 1001);
INSERT INTO EMPLOYEE (EMP_ID, EMP_NAME, GENDER, JOINING_DATE, PHONE_NUMBER, DEPT_ID) VALUES (102, 'PAVAN', 'M', '2020-11-10', NULL,1002);
INSERT INTO EMPLOYEE (EMP_ID, EMP_NAME, GENDER, JOINING_DATE, PHONE_NUMBER, DEPT_ID) VALUES (103, 'NITISH', 'M',  '2020-10-12', NULL, 1002);
INSERT INTO EMPLOYEE (EMP_ID, EMP_NAME, GENDER, JOINING_DATE, PHONE_NUMBER, DEPT_ID) VALUES (104, 'ROHIT', 'M',  '2020-09-21', '7655454545', 1001);
INSERT INTO EMPLOYEE (EMP_ID, EMP_NAME, GENDER, JOINING_DATE, PHONE_NUMBER, DEPT_ID) VALUES (105, 'VIRAT', 'M',  '2020-07-18', '9844738398', 1000);
INSERT INTO EMPLOYEE (EMP_ID, EMP_NAME, GENDER, JOINING_DATE, DEPT_ID) VALUES (106, 'SITA', 'F',  '2020-08-15', 1000);
INSERT INTO EMPLOYEE (EMP_ID, EMP_NAME, GENDER, JOINING_DATE, DEPT_ID) VALUES (107, 'TANUJA', 'F',  '2020-02-28', 1001);



select * from employee;

select emp_ID,EMP_NAME, PHONE_NUMBER from employee;

select emp_ID,EMP_NAME, PHONE_NUMBER from employee where phone_number is null;

select emp_ID,EMP_NAME, PHONE_NUMBER from employee where phone_number is not null;


