/*

RegExps

*/

CREATE TABLE TEST_EXP 
(
	ID INT PRIMARY KEY,
    VALUE VARCHAR(100)
);

INSERT INTO TEST_EXP VALUES (1, 'AAA');
INSERT INTO TEST_EXP VALUES (2, 'AAB');
INSERT INTO TEST_EXP VALUES (3, 'ABC');

INSERT INTO TEST_EXP VALUES (4, 'BAA');
INSERT INTO TEST_EXP VALUES (5, 'BAB');
INSERT INTO TEST_EXP VALUES (6, 'BBC');
INSERT INTO TEST_EXP VALUES (7, 'XBC');
INSERT INTO TEST_EXP VALUES (8, 'BCBCBB');
INSERT INTO TEST_EXP VALUES (9, 'BAAAACBB');
INSERT INTO TEST_EXP VALUES (10, 'BAACAAB');
INSERT INTO TEST_EXP VALUES (11, 'BCBACAAABAAB');
INSERT INTO TEST_EXP VALUES (12, 'BCBACAAABAABCBC');
INSERT INTO TEST_EXP VALUES (13, 'BCBACAAAAABAABCBC');
INSERT INTO TEST_EXP VALUES (14, 'AB');
INSERT INTO TEST_EXP VALUES (15, 'AAB');
INSERT INTO TEST_EXP VALUES (16, 'AAAB');
INSERT INTO TEST_EXP VALUES (17, 'AAAAB');
INSERT INTO TEST_EXP VALUES (18, 'AAAAAB');


SELECT * FROM TEST_EXP WHERE VALUE REGEXP '^A';
SELECT * FROM TEST_EXP WHERE VALUE REGEXP '^AA';

SELECT * FROM TEST_EXP WHERE VALUE REGEXP 'BC$';

SELECT * FROM TEST_EXP WHERE VALUE REGEXP 'B';


/*
STARTS WITH
ENDS WITH
CONTAINS
{N} REPEAT
[..]
[^..]
exp1|exp2
{m,n}


*
+
.
*/



SELECT * FROM TEST_EXP WHERE VALUE REGEXP 'A{2}';

SELECT * FROM TEST_EXP WHERE VALUE REGEXP '^[^ABCD]';


SELECT * FROM TEST_EXP WHERE VALUE REGEXP '(BC){2}';
SELECT * FROM TEST_EXP WHERE VALUE REGEXP '(CB){2}';


SELECT * FROM TEST_EXP WHERE VALUE REGEXP '(AA){2}|(CB){2}';
SELECT * FROM TEST_EXP WHERE VALUE REGEXP '(AA)|(CB)';

SELECT * FROM TEST_EXP WHERE VALUE REGEXP '^A{2,4}B';

